# Adds namespace to all resources.

# Value of this field is prepended to the
# names of all resources, e.g. a deployment named
# "wordpress" becomes "alices-wordpress".
# Note that it should also match with the prefix (text before '-') of the namespace
# field above.

# Labels to add to all resources and selectors.

resources:
  - ../default
  - ../samples
  - ../scorecard
  - bases/metrics-operator.clusterserviceversion.yaml

vars:
  - name: REPORTER_IMAGE_MARKER
    objref:
      kind: Deployment
      name: controller-manager
      apiVersion: apps/v1
    fieldref:
      fieldpath: metadata.annotations.reporterImage
  - name: METRIC_STATE_IMAGE_MARKER
    objref:
      kind: Deployment
      name: controller-manager
      apiVersion: apps/v1
    fieldref:
      fieldpath: metadata.annotations.metricStateImage
  - name: AUTHCHECK_IMAGE_MARKER
    objref:
      kind: Deployment
      name: controller-manager
      apiVersion: apps/v1
    fieldref:
      fieldpath: metadata.annotations.authcheckImage
