# Adds namespace to all resources.

# Value of this field is prepended to the
# names of all resources, e.g. a deployment named
# "wordpress" becomes "alices-wordpress".
# Note that it should also match with the prefix (text before '-') of the namespace
# field above.

# Labels to add to all resources and selectors.

resources:
  - ../default
  - ../samples
  - ../scorecard
  - bases/ibm-metrics-operator.clusterserviceversion.yaml
