# This patch inject a sidecar container which is a HTTP proxy for the 
# controller manager, it performs RBAC authorization against the Kubernetes API using SubjectAccessReviews.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: system
spec:
  template:
    spec:
      containers:
      - name: manager
        args:
        - "--health-probe-bind-address=:8081"
        - "--metrics-addr=127.0.0.1:8080"
        - "--enable-leader-election"
      - name: mgr-kube-rbac-proxy
        image: registry.redhat.io/openshift4/ose-kube-rbac-proxy:v4.5
        args:
        - "--secure-listen-address=0.0.0.0:8443"
        - "--upstream=http://127.0.0.1:8081/"
        - "--logtostderr=true"
        - "--tls-cert-file=/tmp/k8s-webhook-server/serving-certs/tls.crt"
        - "--tls-private-key-file=/tmp/k8s-webhook-server/serving-certs/tls.key"
        - "--v=10"
        ports:
        - containerPort: 8443
          name: monitoring-https
        - containerPort: 9443
          name: https
