apiVersion: skaffold/v2beta28
kind: Config
metadata:
  name: redhat-marketplace-operator
build:
  artifacts:
  - image: ibm-metrics-operator
    context: .
    custom:
      buildCommand: ARCHS=amd64 make vet docker-build
      dependencies:
        paths:
        - go.mod
        - go.sum
        - main.go
        - apis/**
        - controllers/**
        - pkg/**
        - assets/**
        - Dockerfile
        ignore:
        - ./**/*_test.go
  - image: redhat-marketplace-reporter
    context: ../reporter/v2
    custom:
      buildCommand: ARCHS=amd64 make vet docker-build
      dependencies:
        paths:
        - go.mod
        - go.sum
        - cmd/**
        - pkg/**
        - Dockerfile
        ignore:
        - ./**/*_test.go
  - image: redhat-marketplace-metric-state
    context: ../metering/v2
    custom:
      buildCommand: ARCHS=amd64 make vet docker-build
      dependencies:
        paths:
        - go.mod
        - go.sum
        - cmd/**
        - internal/**
        - pkg/**
        - ./**/*.go
        - Dockerfile
        ignore:
        - ./**/*_test.go
  - image: redhat-marketplace-authcheck
    context: ../authchecker/v2
    custom:
      buildCommand: ARCHS=amd64 make vet docker-build
      dependencies:
        paths:
        - go.mod
        - go.sum
        - cmd/**
        - pkg/**
        - Dockerfile
        ignore:
        - '**/*_test.go'
  - image: redhat-marketplace-data-service
    context: ../airgap/v2
    custom:
      buildCommand: ARCHS=amd64 make vet docker-build
      dependencies:
        paths:
        - go.mod
        - go.sum
        - apis/**
        - cmd/server/**
        - pkg/**
        - internal/**
        - Dockerfile
        ignore:
        - '**/*_test.go'
  - image: ibm-data-reporter-operator
    context: ../datareporter/v2
    custom:
      buildCommand: ARCHS=amd64 make vet docker-build
      dependencies:
        paths:
        - go.mod
        - go.sum
        - main.go
        - ../../v2/apis/**
        - controllers/**
        - ../../v2/pkg/**
        - ../../v2/assets/**
        - Dockerfile
        ignore:
        - '**/*_test.go'
  tagPolicy:
    customTemplate:
      template: '{{ .VERS }}-{{ .GC }}'
      components:
      - name: VERS
        envTemplate:
          template: '{{.VERSION}}'
      - name: GC
        gitCommit:
          variant: AbbrevCommitSha
  local:
    useBuildkit: true
    concurrency: 2
deploy:
  helm:
    releases:
    - name: ibm-metrics-operator
      chartPath: ./config/helm-wrapper
      valuesFiles:
      - ./config/helm-wrapper/values.yaml
      - ./config/helm-wrapper/devValues.yaml
      artifactOverrides:
        authCheckImage: redhat-marketplace-authcheck
        dqLiteImage: redhat-marketplace-data-service
        metricStateImage: redhat-marketplace-metric-state
        operatorImage: ibm-metrics-operator
        reporterImage: redhat-marketplace-reporter
        dataReporterImage: ibm-data-reporter-operator
      namespace: openshift-redhat-marketplace
      setValueTemplates:
        devEnvVars[0].name: RELATED_IMAGE_METERDEF_FILE_SERVER
        devEnvVars[0].value: '{{.IMAGE_REGISTRY}}/rhm-meterdefinition-file-server:v1'
      upgradeOnChange: true
    flags:
      install:
      - --post-renderer
      - config/helm-wrapper/kustomize
      upgrade:
      - --post-renderer
      - config/helm-wrapper/kustomize
portForward:
- resourceType: Deployment
  resourceName: rhm-metric-state
  port: 8080
