apiVersion: skaffold/v3
kind: Config
metadata:
  name: redhat-marketplace-operator
build:
  artifacts:
  - image: ibm-metrics-operator
    context: .
    custom:
      buildCommand: ARCHS=amd64 make vet docker-build docker-push kustomize-set
      dependencies:
        paths:
        - go.mod
        - go.sum
        - main.go
        - apis/**
        - controllers/**
        - pkg/**
        - assets/**
        - Dockerfile
        ignore:
        - ./**/*_test.go
  - image: redhat-marketplace-reporter
    context: ../reporter/v2
    custom:
      buildCommand: ARCHS=amd64 make vet docker-build docker-push
      dependencies:
        paths:
        - go.mod
        - go.sum
        - cmd/**
        - pkg/**
        - Dockerfile
        ignore:
        - ./**/*_test.go
  - image: redhat-marketplace-metric-state
    context: ../metering/v2
    custom:
      buildCommand: ARCHS=amd64 make vet docker-build docker-push
      dependencies:
        paths:
        - go.mod
        - go.sum
        - cmd/**
        - internal/**
        - pkg/**
        - ./**/*.go
        - Dockerfile
        ignore:
        - ./**/*_test.go
  - image: redhat-marketplace-authcheck
    context: ../authchecker/v2
    custom:
      buildCommand: ARCHS=amd64 make vet docker-build docker-push
      dependencies:
        paths:
        - go.mod
        - go.sum
        - cmd/**
        - pkg/**
        - Dockerfile
        ignore:
        - '**/*_test.go'
  - image: redhat-marketplace-data-service
    context: ../airgap/v2
    custom:
      buildCommand: ARCHS=amd64 make docker-build docker-push
      dependencies:
        paths:
        - go.mod
        - go.sum
        - apis/**
        - cmd/server/**
        - pkg/**
        - internal/**
        - Dockerfile
        ignore:
        - '**/*_test.go'
  tagPolicy:
    customTemplate:
      template: '{{ .VERS }}-{{ .GC }}'
      components:
      - name: VERS
        envTemplate:
          template: '{{.VERSION}}'
      - name: GC
        gitCommit:
          variant: AbbrevCommitSha
  local:
    useBuildkit: true
    concurrency: 2
manifests:
  kustomize:
    paths: 
    - config/default
deploy:
  kubectl: {}
portForward:
- resourceType: Deployment
  resourceName: rhm-metric-state
  port: 8080
