kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: data-service-binding
  namespace: openshift-config
subjects:
- kind: ServiceAccount
  name: data-service
  namespace: system
roleRef:
  kind: ClusterRole
  name: data-service
  apiGroup: rbac.authorization.k8s.io
