kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: metric-state-binding
  namespace: openshift-config
subjects:
- kind: ServiceAccount
  name: metric-state
  namespace: system
roleRef:
  kind: ClusterRole
  name: metric-state
  apiGroup: rbac.authorization.k8s.io
