kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: reporter-binding
  namespace: system
subjects:
- kind: ServiceAccount
  name: reporter
  namespace: system
roleRef:
  kind: ClusterRole
  name: reporter
  apiGroup: rbac.authorization.k8s.io
