kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: reporter-binding
  namespace: openshift-config
subjects:
- kind: ServiceAccount
  name: reporter
  namespace: system
roleRef:
  kind: Role
  name: reporter
  apiGroup: rbac.authorization.k8s.io
