apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: reporter
rules:
  - apiGroups:
      - ''
    resources:
      - services
    verbs:
      - get
      - watch
      - list
  - nonResourceURLs:
    - /api/v1/query
    - /api/v1/query_range
    - /api/v1/targets
    verbs:
    - create
    - get
  - nonResourceURLs:
    - /dataservice.v1.fileserver.FileServer/*
    verbs:
    - create
