
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- nonResourceURLs:
  - /api/v1/query
  - /api/v1/query_range
  - /api/v1/targets
  verbs:
  - create
  - get
- nonResourceURLs:
  - /community-meterdef-index/*
  verbs:
  - get
- nonResourceURLs:
  - /get-community-meterdefs
  verbs:
  - create
  - get
  - post
- nonResourceURLs:
  - /get-system-meterdefs/*
  verbs:
  - create
  - get
  - post
- nonResourceURLs:
  - /global-community-meterdef-index
  verbs:
  - get
- nonResourceURLs:
  - /global-system-meterdef-index
  verbs:
  - get
- nonResourceURLs:
  - /system-meterdef-index/*
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - configmaps
  - namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
  - get
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
  - get
- apiGroups:
  - config.openshift.io
  resources:
  - clusterversions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - deploy.razee.io
  resources:
  - '*'
  verbs:
  - delete
  - get
  - list
- apiGroups:
  - marketplace.redhat.com
  resources:
  - meterdefinitions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - marketplace.redhat.com
  resources:
  - meterdefinitions
  - meterdefinitions/status
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operators.coreos.com
  resources:
  - catalogsources
  verbs:
  - create
  - get
  - list
  - watch
- apiGroups:
  - operators.coreos.com
  resourceNames:
  - ibm-operator-catalog
  - opencloud-operators
  resources:
  - catalogsources
  verbs:
  - delete
- apiGroups:
  - operators.coreos.com
  resources:
  - clusterserviceversions
  verbs:
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operators.coreos.com
  resources:
  - clusterserviceversions
  - subscriptions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - operators.coreos.com
  resources:
  - operatorgroups
  verbs:
  - create
  - delete
  - get
  - list
  - watch
- apiGroups:
  - operators.coreos.com
  resources:
  - subscriptions
  verbs:
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resourceNames:
  - razeedeploy-admin-cr
  - redhat-marketplace-razeedeploy
  resources:
  - clusterroles
  verbs:
  - delete
- apiGroups:
  - storage.k8s.io
  resources:
  - storageclasses
  verbs:
  - get
  - list
  - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: manager-role
  namespace: system
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - get
  - list
  - watch
- apiGroups:
  - ""
  resourceNames:
  - kubelet-serving-ca-bundle
  - serving-certs-ca-bundle
  resources:
  - configmaps
  verbs:
  - delete
  - patch
  - update
- apiGroups:
  - ""
  resourceNames:
  - razee-cluster-metadata
  - watch-keeper-config
  - watch-keeper-limit-poll
  - watch-keeper-non-namespaced
  resources:
  - configmaps
  verbs:
  - delete
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - delete
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - secret
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resourceNames:
  - ibm-entitlement-key
  - redhat-marketplace-pull-secret
  - rhm-operator-secret
  resources:
  - secrets
  verbs:
  - delete
  - patch
  - update
- apiGroups:
  - ""
  resourceNames:
  - rhm-data-service-mtls
  resources:
  - secrets
  verbs:
  - delete
  - patch
  - update
- apiGroups:
  - ""
  resourceNames:
  - razeedeploy-sa
  - watch-keeper-sa
  resources:
  - serviceaccounts
  verbs:
  - delete
- apiGroups:
  - ""
  resources:
  - serviceaccounts/token
  verbs:
  - create
  - get
  - list
  - update
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - get
  - list
  - watch
- apiGroups:
  - ""
  resourceNames:
  - kube-state-metrics
  - prometheus-operator
  - rhm-metric-state-service
  - rhm-prometheus-meterbase
  resources:
  - services
  verbs:
  - delete
  - patch
  - update
- apiGroups:
  - ""
  resourceNames:
  - rhm-data-service
  resources:
  - services
  verbs:
  - delete
  - patch
  - update
- apiGroups:
  - ""
  resourceNames:
  - rhm-meterdefinition-file-server
  resources:
  - services
  verbs:
  - delete
  - patch
  - update
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - get
  - list
  - watch
- apiGroups:
  - apps
  resourceNames:
  - clustersubscription
  - featureflagsetld-controller
  - managedset-controller
  - mustachetemplate-controller
  - remoteresource-controller
  - remoteresources3-controller
  - remoteresources3decrypt-controller
  - watch-keeper
  resources:
  - deployments
  verbs:
  - delete
- apiGroups:
  - apps
  resourceNames:
  - prometheus-operator
  - rhm-metric-state
  resources:
  - deployments
  verbs:
  - delete
  - patch
  - update
- apiGroups:
  - apps
  resourceNames:
  - rhm-remoteresources3-controller
  - rhm-watch-keeper
  resources:
  - deployments
  verbs:
  - delete
  - patch
  - update
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - create
  - get
  - list
  - watch
- apiGroups:
  - apps
  resourceNames:
  - rhm-data-service
  resources:
  - statefulsets
  verbs:
  - delete
  - patch
  - update
- apiGroups:
  - apps.openshift.io
  resources:
  - deploymentconfigs
  verbs:
  - create
  - get
  - list
  - watch
- apiGroups:
  - apps.openshift.io
  resourceNames:
  - rhm-meterdefinition-file-server
  resources:
  - deploymentconfigs
  verbs:
  - delete
  - patch
  - update
- apiGroups:
  - batch
  - extensions
  resources:
  - cronjobs
  - jobs
  verbs:
  - create
  - get
  - list
  - watch
- apiGroups:
  - batch
  - extensions
  resourceNames:
  - rhm-meter-report-upload
  resources:
  - cronjobs
  - jobs
  verbs:
  - delete
  - patch
  - update
- apiGroups:
  - batch
  - extensions
  resources:
  - jobs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - batch
  - extensions
  resourceNames:
  - razeedeploy-job
  resources:
  - jobs
  verbs:
  - delete
- apiGroups:
  - image.openshift.io
  resources:
  - imagestreams
  verbs:
  - create
  - get
  - list
  - watch
- apiGroups:
  - image.openshift.io
  resourceNames:
  - rhm-meterdefinition-file-server
  resources:
  - imagestreams
  verbs:
  - delete
  - patch
  - update
- apiGroups:
  - marketplace.redhat.com
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - marketplace.redhat.com
  resources:
  - marketplaceconfigs
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - marketplace.redhat.com
  resources:
  - marketplaceconfigs
  - marketplaceconfigs/finalizers
  - marketplaceconfigs/status
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - marketplace.redhat.com
  resources:
  - meterbases
  verbs:
  - create
  - get
  - list
  - watch
- apiGroups:
  - marketplace.redhat.com
  resourceNames:
  - rhm-marketplaceconfig-meterbase
  resources:
  - meterbases
  verbs:
  - delete
  - patch
  - update
- apiGroups:
  - marketplace.redhat.com
  resources:
  - meterbases
  - meterbases/finalizers
  - meterbases/status
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - marketplace.redhat.com
  resources:
  - meterreports
  verbs:
  - create
  - delete
  - get
  - list
  - watch
- apiGroups:
  - marketplace.redhat.com
  resources:
  - meterreports
  - meterreports/finalizers
  - meterreports/status
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - marketplace.redhat.com
  resources:
  - razeedeployments
  verbs:
  - create
  - get
  - list
  - watch
- apiGroups:
  - marketplace.redhat.com
  resourceNames:
  - rhm-marketplaceconfig-razeedeployment
  resources:
  - razeedeployments
  verbs:
  - delete
  - patch
  - update
- apiGroups:
  - marketplace.redhat.com
  resources:
  - razeedeployments
  - razeedeployments/finalizers
  - razeedeployments/status
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - marketplace.redhat.com
  resources:
  - remoteresources3s
  verbs:
  - create
  - get
  - list
  - watch
- apiGroups:
  - marketplace.redhat.com
  resourceNames:
  - child
  - parent
  resources:
  - remoteresources3s
  verbs:
  - delete
  - patch
  - update
- apiGroups:
  - marketplace.redhat.com
  resources:
  - remoteresources3s
  - remoteresources3s/status
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - monitoring.coreos.com
  resourceNames:
  - rhm-marketplaceconfig-meterbase
  resources:
  - prometheuses
  verbs:
  - delete
  - patch
  - update
- apiGroups:
  - monitoring.coreos.com
  resources:
  - prometheuses
  - servicemonitors
  verbs:
  - create
  - get
  - list
  - watch
- apiGroups:
  - monitoring.coreos.com
  resourceNames:
  - kube-state-metrics
  - prometheus-user-workload
  - redhat-marketplace-kube-state-metrics
  - redhat-marketplace-kubelet
  - rhm-metric-state
  - rhm-prometheus-meterbase
  resources:
  - servicemonitors
  verbs:
  - delete
  - patch
  - update
- apiGroups:
  - route.openshift.io
  resources:
  - routes
  verbs:
  - create
  - get
  - list
  - watch
- apiGroups:
  - route.openshift.io
  resourceNames:
  - rhm-data-service
  resources:
  - routes
  verbs:
  - delete
  - patch
  - update
