apiVersion: batch/v1
kind: CronJob
metadata:
  name: rhm-meter-report
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccount: redhat-marketplace-operator
          restartPolicy: Never
          containers:
            - name: reporter
              image: redhat-markplace-reporter
              imagePullPolicy: Always
              # additional args are added in factory
              args:
                [
                  'upload',
                  '--cafile',
                  '/etc/configmaps/operator-cert-ca-bundle/service-ca.crt',
                  '--tokenfile',
                  '/etc/auth-service-account/token',
                ]
              runAsUser:
              volumeMounts:
                - mountPath: /etc/configmaps/operator-cert-ca-bundle
                  name: operator-certs-ca-bundle
                  readOnly: true
                - mountPath: /etc/auth-service-account
                  name: token-vol
                  readOnly: true
          volumes:
            - configMap:
                name: operator-certs-ca-bundle
              name: operator-certs-ca-bundle
            - name: token-vol
              projected:
                sources:
                  - serviceAccountToken:
                      audience: rhm-prometheus-meterbase.openshift-redhat-marketplace.svc
                      expirationSeconds: 3600
                      path: token