---
# Source: redhat-marketplace-operator-template-chart/templates/role_binding.yaml
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: reporter-binding
  namespace: openshift-config
subjects:
- kind: ServiceAccount
  name: reporter
  namespace: system
roleRef:
  kind: Role
  name: reporter
  apiGroup: rbac.authorization.k8s.io
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: reporter-binding
  namespace: system
subjects:
- kind: ServiceAccount
  name: reporter
  namespace: system
roleRef:
  kind: ClusterRole
  name: reporter
  apiGroup: rbac.authorization.k8s.io
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: reporter-cluster-monitoring-binding
  namespace: system
subjects:
- kind: ServiceAccount
  name: reporter
  namespace: system
roleRef:
  kind: ClusterRole
  name: cluster-monitoring-view
  apiGroup: rbac.authorization.k8s.io
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: metric-state-binding
  namespace: openshift-config
subjects:
- kind: ServiceAccount
  name: metric-state
  namespace: system
roleRef:
  kind: ClusterRole
  name: metric-state
  apiGroup: rbac.authorization.k8s.io
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: data-service-binding
  namespace: openshift-config
subjects:
- kind: ServiceAccount
  name: data-service
  namespace: system
roleRef:
  kind: ClusterRole
  name: data-service
  apiGroup: rbac.authorization.k8s.io
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: servicemonitor-metrics-reader-binding
  namespace: system
subjects:
- kind: ServiceAccount
  name: servicemonitor-metrics-reader
  namespace: system
roleRef:
  kind: ClusterRole
  name: servicemonitor-metrics-reader
  apiGroup: rbac.authorization.k8s.io