---
# Source: redhat-marketplace-operator-template-chart/templates/role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: reporter
  namespace: system
rules:
  - apiGroups:
      - ''
    resources:
      - secrets
    verbs:
      - get
      - watch
      - list
  - apiGroups:
      - ''
    resources:
      - events
    verbs:
      - get
      - watch
      - list
      - create
      - update
      - patch
  - apiGroups:
      - batch
    resources:
      - jobs
    verbs:
      - get
      - watch
      - list
  - apiGroups:
      - marketplace.redhat.com
    resources:
      - meterreports
      - marketplaceconfigs
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - marketplace.redhat.com
    resources:
      - meterreports
      - meterreports/status
    verbs:
      - update
      - patch
---
# Source: redhat-marketplace-operator-template-chart/templates/role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: reporter
rules:
  - apiGroups:
      - ''
    resources:
      - services
    verbs:
      - get
      - watch
      - list
  - nonResourceURLs:
    - /api/v1/query
    - /api/v1/query_range
    - /api/v1/targets
    verbs:
    - create
    - get
  - nonResourceURLs:
    - /dataservice.v1.fileserver.FileServer/*
    verbs:
    - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: metric-state
rules:
  - apiGroups:
      - 'marketplace.redhat.com'
    resources:
      - 'meterreports'
    verbs:
      - get
      - list
      - watch
      - update
  - apiGroups:
      - 'marketplace.redhat.com'
    resources:
      - 'meterdefinitions'
      - 'meterdefinitions/status'
    verbs:
      - get
      - list
      - watch
      - update
  - apiGroups:
      - operators.coreos.com
    resources:
      - operatorgroups
    verbs:
      - get
      - list
  - apiGroups:
    - monitoring.coreos.com
    resources:
    - servicemonitors
    verbs:
    - get
    - list
    - watch
    - update
  - apiGroups:
      - authentication.k8s.io
    resources:
      - tokenreviews
    verbs:
      - create
  - apiGroups:
      - authorization.k8s.io
    resources:
      - subjectaccessreviews
    verbs:
      - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: data-service
rules:
  - apiGroups:
      - authentication.k8s.io
    resources:
      - tokenreviews
    verbs:
      - create
  - apiGroups:
      - authorization.k8s.io
    resources:
      - subjectaccessreviews
    verbs:
      - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: servicemonitor-metrics-reader
  namespace: system
rules:
  - nonResourceURLs:
    - /metrics
    verbs:
      - get
