---
# Source: redhat-marketplace-operator-template-chart/templates/service_account.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: operator
  namespace: system
  labels:
    redhat.marketplace.com/name: metering-operator
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: metric-state
  namespace: system
  labels:
    redhat.marketplace.com/name: metering-operator
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: reporter
  namespace: system
  labels:
    redhat.marketplace.com/name: metering-operator
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: servicemonitor-metrics-reader
  namespace: system
  labels:
    redhat.marketplace.com/name: metering-operator