# Adds namespace to all resources.
namespace: openshift-redhat-marketplace
# Value of this field is prepended to the
# names of all resources, e.g. a deployment named
# "wordpress" becomes "alices-wordpress".
# Note that it should also match with the prefix (text before '-') of the namespace
# field above.

# Labels to add to all resources and selectors.
commonLabels:
  redhat.marketplace.com/name: redhat-marketplace-operator

resources:
  - ../rbac
  - ../manager
  - ../scorecard

#patchesStrategicMerge:
#- manager_auth_proxy_patch.yaml
#- manager_webhook_patch.yaml

configurations:
  - kustomizeconfig.yaml
vars:
  - name: AUTHCHECK_IMAGE_MARKER
    objref:
      kind: Deployment
      name: deployer-controller-manager
      apiVersion: apps/v1
    fieldref:
      fieldpath: metadata.annotations.authcheckImage
