resources:
- manager.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
- files:
  - component_config.yaml
  name: component-config
images:
- name: data-reporter-operator
  newName: image-registry.openshift-image-registry.svc:5000/openshift/data-reporter-operator
  newTag: tag-1681939331
