apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    redhat.marketplace.com/name: redhat-marketplace-operator
  name: redhat-marketplace-controller-manager-service
spec:
  ports:
  - port: 9443
    targetPort: 9443
  selector:
    control-plane: controller-manager
    redhat.marketplace.com/name: redhat-marketplace-operator
status:
  loadBalancer: {}
