apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  creationTimestamp: "2021-05-31T23:33:31Z"
  generation: 2
  labels:
    app: rhm-meterdefinition-file-server
  name: rhm-meterdefinition-file-server
  namespace: openshift-redhat-marketplace
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    deploymentconfig: rhm-meterdefinition-file-server
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      annotations:
        # openshift.io/generated-by: OpenShiftNewApp
      # creationTimestamp: null
      labels:
        deploymentconfig: rhm-meterdefinition-file-server
    spec:
      containers:
      - image: quay.io/mxpaspa/rhm-meterdefinition-file-server@sha256:d289efcef33ea176ef58cea26796880baddc2348ebde528824d430fdec52b913
        imagePullPolicy: IfNotPresent
        name: rhm-meterdefinition-file-server
        ports:
        - containerPort: 8100
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - rhm-meterdefinition-file-server
      from:
        kind: ImageStreamTag
        name: rhm-meterdefinition-file-server:v1.0.0-0f453c86e4d568ed1455f3faa274d97f39d8a7d1
        namespace: openshift-redhat-marketplace
      # lastTriggeredImage: quay.io/mxpaspa/rhm-meterdefinition-file-server@sha256:d289efcef33ea176ef58cea26796880baddc2348ebde528824d430fdec52b913
    type: ImageChange
# status:
#   availableReplicas: 1
#   conditions:
#   - lastTransitionTime: "2021-05-31T23:34:19Z"
#     lastUpdateTime: "2021-05-31T23:34:19Z"
#     message: Deployment config has minimum availability.
#     status: "True"
#     type: Available
#   - lastTransitionTime: "2021-05-31T23:33:36Z"
#     lastUpdateTime: "2021-05-31T23:34:20Z"
#     message: replication controller "rhm-meterdefinition-file-server-1" successfully
#       rolled out
#     reason: NewReplicationControllerAvailable
#     status: "True"
#     type: Progressing
#   details:
#     causes:
#     - type: ConfigChange
#     message: config change
#   latestVersion: 1
#   observedGeneration: 2
#   readyReplicas: 1
#   replicas: 1
#   unavailableReplicas: 0
#   updatedReplicas: 1
