apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: rhm-meterdefinition-file-server-tls
  labels:
    app: rhm-meterdefinition-file-server
  name: rhm-meterdefinition-file-server
  namespace: openshift-redhat-marketplace
spec:
  ports:
  - name: https
    port: 8200
    protocol: TCP
    targetPort: 8200
  selector:
    deploymentconfig: rhm-meterdefinition-file-server
  sessionAffinity: None
  type: ClusterIP
