apiVersion: v1
kind: Service
metadata:
  labels:
    app: rhm-meterdefinition-file-server
  name: rhm-meterdefinition-file-server
  namespace: openshift-redhat-marketplace

spec:
  ports:
  - name: 8100-tcp
    port: 8100
    protocol: TCP
    targetPort: 8100
  selector:
    deploymentconfig: rhm-meterdefinition-file-server
  sessionAffinity: None
  type: ClusterIP
