# permissions for end users to view componentconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: componentconfig-viewer-role
rules:
- apiGroups:
  - marketplace.redhat.com
  resources:
  - componentconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - marketplace.redhat.com
  resources:
  - componentconfigs/status
  verbs:
  - get
