# permissions for end users to edit componentconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: componentconfig-editor-role
rules:
- apiGroups:
  - marketplace.redhat.com
  resources:
  - componentconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - marketplace.redhat.com
  resources:
  - componentconfigs/status
  verbs:
  - get
