# permissions for end users to edit datareporterconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: datareporterconfig-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: data-reporter-operator
    app.kubernetes.io/part-of: data-reporter-operator
    app.kubernetes.io/managed-by: kustomize
  name: datareporterconfig-editor-role
rules:
- apiGroups:
  - cache.marketplace.redhat.com
  resources:
  - datareporterconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cache.marketplace.redhat.com
  resources:
  - datareporterconfigs/status
  verbs:
  - get
