kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: servicemonitor-metrics-reader-binding
  namespace: system
subjects:
- kind: ServiceAccount
  name: servicemonitor-metrics-reader
  namespace: system
roleRef:
  kind: ClusterRole
  name: servicemonitor-metrics-reader
  apiGroup: rbac.authorization.k8s.io
