apiVersion: v1
data:
  config.yaml: ImF1dGhvcml6YXRpb24iOgogICJyZXNvdXJjZUF0dHJpYnV0ZXMiOgogICAgImFwaVZlcnNpb24iOiAibWV0cmljcy5rOHMuaW8vdjFiZXRhMSIKICAgICJuYW1lc3BhY2UiOiAie3sgLlZhbHVlIH19IgogICAgInJlc291cmNlIjogInBvZHMiCiAgInJld3JpdGVzIjoKICAgICJieVF1ZXJ5UGFyYW1ldGVyIjoKICAgICAgIm5hbWUiOiAibmFtZXNwYWNlIg==
kind: Secret
metadata:
  labels:
    k8s-app: rhm-prometheus-meterbase
  name: kube-rbac-proxy
type: Opaque
