apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: rhm-prometheus-meterbase-tls
  labels:
    prometheus: redhat-marketplace
  name: rhm-prometheus-meterbase
spec:
  ports:
  - name: https
    port: 9091
    targetPort: https
  - name: rbac
    port: 9092
    targetPort: rbac
  selector:
    app: prometheus
    prometheus: meterbase
  sessionAffinity: ClientIP
  type: ClusterIP
