commonLabels:
  redhat.marketplace.com/name: redhat-marketplace-operator

resources:
- ../default
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: openshift-redhat-marketplace
