# Secret for redhat-marketplace-servicemonitor-metrics-reader ServiceAccount for ServiceMonitor bearerTokenSecret
apiVersion: v1
kind: Secret
metadata:
  name: servicemonitor-metrics-reader
  labels:
    name: servicemonitor-metrics-reader
  annotations:
    kubernetes.io/service-account.name: redhat-marketplace-servicemonitor-metrics-reader
type: kubernetes.io/service-account-token
