# Secret for metrics-servicemonitor-metrics-reader ServiceAccount for ServiceMonitor bearerTokenSecret
apiVersion: v1
kind: Secret
metadata:
  name: servicemonitor-metrics-reader
  labels:
    name: servicemonitor-metrics-reader
  annotations:
    kubernetes.io/service-account.name: metrics-servicemonitor-metrics-reader
type: kubernetes.io/service-account-token
