apiVersion: marketplace.redhat.com/v1beta1
kind: MeterDefinition
metadata:
  name: rhm-prometheus-meterbase-uptime
  namespace: openshift-redhat-marketplace
spec:
  group: marketplace.redhat.com
  kind: Pod
  meters:
    - aggregation: avg
      metricId: rhm-prometheus-meterbase-uptime
      name: rhm-prometheus-meterbase-uptime
      period: 1h
      query: avg_over_time(up{job="rhm-prometheus-meterbase"}[5m])
      workloadType: Pod
  resourceFilters:
    - label:
        labelSelector:
          matchLabels:
            prometheus: rhm-marketplaceconfig-meterbase
      workloadType: Pod
