# permissions for end users to edit meterdefinitions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: meterdefinition-editor-role
rules:
- apiGroups:
  - marketplace.redhat.com
  resources:
  - meterdefinitions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - marketplace.redhat.com
  resources:
  - meterdefinitions/status
  verbs:
  - get
