kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: remoteresourcedeployment-binding
subjects:
- kind: ServiceAccount
  name: remoteresourcedeployment
  namespace: system
roleRef:
  kind: ClusterRole
  name: remoteresourcedeployment
  apiGroup: rbac.authorization.k8s.io
