kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: remoteresourcedeployment-binding
  namespace: system
subjects:
- kind: ServiceAccount
  name: remoteresourcedeployment
  namespace: system
roleRef:
  kind: Role
  name: remoteresourcedeployment
  apiGroup: rbac.authorization.k8s.io
