apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: remoteresources3deployment
rules:
  - apiGroups:
      - operators.coreos.com
    resources:
      - subscriptions
    verbs:
      - '*'
  - apiGroups:
      - marketplace.redhat.com
    resources:
      - remoteresources3s
    verbs:
      - get
      - list
      - watch
  - apiGroups:
    - authentication.k8s.io
    resources:
    - tokenreviews
    verbs:
    - create
