apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: remoteresourcedeployment
  namespace: system
rules:
  - apiGroups:
      - ''
    resources:
      - pods
      - secrets
    verbs:
      - get
      - watch
      - list
  - apiGroups:
      - deploy.razee.io
    resources:
      - remoteresources
      - remoteresources/status
    verbs:
      - '*'
