kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: remoteresources3deployment-binding
  namespace: system
subjects:
- kind: ServiceAccount
  name: remoteresources3deployment
  namespace: system
roleRef:
  kind: Role
  name: remoteresources3deployment
  apiGroup: rbac.authorization.k8s.io
