kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: remoteresources3deployment-binding
subjects:
- kind: ServiceAccount
  name: remoteresources3deployment
  namespace: system
roleRef:
  kind: ClusterRole
  name: remoteresources3deployment
  apiGroup: rbac.authorization.k8s.io
