---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - config.openshift.io
  resources:
  - clusterversions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - deploy.razee.io
  resources:
  - '*'
  verbs:
  - delete
  - get
  - list
- apiGroups:
  - rbac.authorization.k8s.io
  resourceNames:
  - razeedeploy-admin-cr
  - redhat-marketplace-razeedeploy
  resources:
  - clusterroles
  verbs:
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: manager-role
  namespace: system
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - get
  - list
  - watch
- apiGroups:
  - ""
  resourceNames:
  - razee-cluster-metadata
  - watch-keeper-config
  - watch-keeper-limit-poll
  - watch-keeper-non-namespaced
  resources:
  - configmaps
  verbs:
  - delete
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - get
  - list
  - watch
- apiGroups:
  - ""
  resourceNames:
  - clustersubscription
  - rhm-operator-secret
  - watch-keeper-secret
  resources:
  - secrets
  verbs:
  - delete
  - patch
  - update
- apiGroups:
  - ""
  resourceNames:
  - razeedeploy-sa
  - watch-keeper-sa
  resources:
  - serviceaccounts
  verbs:
  - delete
- apiGroups:
  - apps
  resourceNames:
  - clustersubscription
  - featureflagsetld-controller
  - managedset-controller
  - mustachetemplate-controller
  - remoteresource-controller
  - remoteresources3-controller
  - remoteresources3decrypt-controller
  - watch-keeper
  resources:
  - deployments
  verbs:
  - delete
- apiGroups:
  - apps
  resources:
  - deployments
  - deployments/finalizers
  verbs:
  - create
  - get
  - list
  - watch
- apiGroups:
  - apps
  resourceNames:
  - rhm-remoteresources3-controller
  - rhm-watch-keeper
  resources:
  - deployments
  - deployments/finalizers
  verbs:
  - delete
  - patch
  - update
- apiGroups:
  - batch
  - extensions
  resources:
  - jobs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - batch
  - extensions
  resourceNames:
  - razeedeploy-job
  resources:
  - jobs
  verbs:
  - delete
- apiGroups:
  - marketplace.redhat.com
  resources:
  - razeedeployments
  - razeedeployments/finalizers
  - razeedeployments/status
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - marketplace.redhat.com
  resources:
  - remoteresources3s
  verbs:
  - create
  - get
  - list
  - watch
- apiGroups:
  - marketplace.redhat.com
  resourceNames:
  - child
  - parent
  resources:
  - remoteresources3s
  verbs:
  - delete
  - patch
  - update
- apiGroups:
  - marketplace.redhat.com
  resources:
  - remoteresources3s
  - remoteresources3s/status
  verbs:
  - get
  - list
  - patch
  - update
  - watch
