apiVersion: v1
kind: Secret
metadata:
  generateName: redhat-marketplace-service-account-token-
  labels:
    name: redhat-marketplace-service-account-token
  annotations:
    kubernetes.io/service-account.name: redhat-marketplace-operator
type: kubernetes.io/service-account-token
