apiVersion: v1
kind: Secret
metadata:
  name: redhat-marketplace-service-account-token
  labels:
    name: redhat-marketplace-service-account-token
  annotations:
    kubernetes.io/service-account.name: metering-servicemonitor-metrics-reader
type: kubernetes.io/service-account-token
