apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/name: rhm-metric-state
    marketplace.redhat.com/metering: 'true'
  name: rhm-metric-state
spec:
  endpoints:
    - bearerTokenSecret:
        key: token
        name: redhat-marketplace-service-account-token
      honorLabels: true
      interval: 2m
      port: https
      scheme: https
      scrapeTimeout: 2m
      tlsConfig:
        ca:
          configMap:
            key: service-ca.crt
            name: serving-certs-ca-bundle
        serverName: server-name-replaced-at-runtime
    - bearerTokenSecret:
        key: token
        name: redhat-marketplace-service-account-token
      interval: 2m
      port: https-metrics
      scheme: https
      scrapeTimeout: 2m
      tlsConfig:
        ca:
          configMap:
            key: service-ca.crt
            name: serving-certs-ca-bundle
        serverName: server-name-replaced-at-runtime
  jobLabel: k8s-app
  selector:
    matchLabels:
      app.kubernetes.io/component: controller
      app.kubernetes.io/name: rhm-metric-state
