apiVersion: batch/v1
kind: Job
metadata:
  name: razeedeploy-job
  namespace: rhm-marketplace
spec:
  template:
    spec:
      serviceAccountName: redhat-marketplace-operator
      containers:
      - name: razeedeploy-job
        image: "quay.io/razee/razeedeploy-delta:1.1.3"
        command: install,uninstall
      restartPolicy: Never
  backoffLimit: 5
