apiVersion: skaffold/v3
kind: Config
metadata:
  name: redhat-marketplace-operator
build:
  artifacts:
  - image: redhat-marketplace-operator
    context: .
    custom:
      buildCommand: ARCHS=amd64 make vet docker-build docker-push kustomize-set-operator
      dependencies:
        paths:
        - go.mod
        - go.sum
        - main.go
        - ../../v2/apis/**
        - controllers/**
        - ../../v2/pkg/**
        - ../../v2/assets/**
        - Dockerfile
        ignore:
        - ./**/*_test.go
  - image: redhat-marketplace-authcheck
    context: ../../authchecker/v2
    custom:
      buildCommand: ARCHS=amd64 make vet docker-build docker-push kustomize-set-deployer
      dependencies:
        paths:
        - go.mod
        - go.sum
        - cmd/**
        - pkg/**
        - Dockerfile
        ignore:
        - '**/*_test.go'
  tagPolicy:
    dateTime: {}
  local:
    useBuildkit: true
    concurrency: 2
manifests:
  kustomize:
    paths: 
    - config/default
deploy:
  kubectl: {}
