apiVersion: skaffold/v2beta28
kind: Config
metadata:
  name: redhat-marketplace-operator
build:
  artifacts:
  - image: redhat-marketplace-operator
    context: .
    custom:
      buildCommand: ARCHS=amd64 make vet docker-build
      dependencies:
        paths:
        - go.mod
        - go.sum
        - main.go
        - apis/**
        - controllers/**
        - pkg/**
        - assets/**
        - Dockerfile
        ignore:
        - ./**/*_test.go
  tagPolicy:
    customTemplate:
      template: '{{ .VERS }}-{{ .GC }}'
      components:
      - name: VERS
        envTemplate:
          template: '{{.VERSION}}'
      - name: GC
        gitCommit:
          variant: AbbrevCommitSha
  local:
    useBuildkit: true
    concurrency: 2
deploy:
  helm:
    releases:
    - name: rhm-operator
      chartPath: ./config/helm-wrapper
      valuesFiles:
      - ./config/helm-wrapper/values.yaml
      - ./config/helm-wrapper/devValues.yaml
      artifactOverrides:
        authCheckImage: redhat-marketplace-authcheck
        operatorImage: redhat-marketplace-operator
      namespace: openshift-redhat-marketplace
      upgradeOnChange: true
    flags:
      install:
      - --post-renderer
      - config/helm-wrapper/kustomize
      upgrade:
      - --post-renderer
      - config/helm-wrapper/kustomize
