apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: data-reporter-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: DataReporterConfig is the Schema for the datareporterconfigs API
      displayName: Data Reporter Config
      kind: DataReporterConfig
      name: datareporterconfigs.cache.marketplace.redhat.com
      version: v1alpha1
    - description: DataReporterConfig is the Schema for the datareporterconfigs API
      displayName: Data Reporter Config
      kind: DataReporterConfig
      name: datareporterconfigs.marketplace.redhat.com
      version: v1alpha1
    required:
    - description: MarketplaceConfig is configuration manager for our Red Hat Marketplace
        controllers By installing this product you accept the license terms https://ibm.biz/BdfaAY.
      displayName: Marketplace Config
      kind: MarketplaceConfig
      name: marketplaceconfigs.marketplace.redhat.com
      version: v1alpha1
  description: Reports Data Events as a Report to Data Service
  displayName: Data Reporter
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - red hat marketplace
  - operators
  links:
  - name: V2
    url: https://v2.domain
  maturity: alpha
  provider:
    name: Red Hat Marketplace
    url: https://github.com/redhat-marketplace/redhat-marketplace-operator
  version: 0.0.0
