apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: ibm-data-reporter-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: DataReporterConfig is the Schema for the datareporterconfigs API
      displayName: Data Reporter Config
      kind: DataReporterConfig
      name: datareporterconfigs.cache.marketplace.redhat.com
      version: v1alpha1
    - description: DataReporterConfig is the Schema for the datareporterconfigs API
      displayName: Data Reporter Config
      kind: DataReporterConfig
      name: datareporterconfigs.marketplace.redhat.com
      version: v1alpha1
    required:
    - description: MarketplaceConfig is configuration manager for our Red Hat Marketplace
        controllers By installing this product you accept the license terms https://ibm.biz/BdfaAY.
      displayName: Marketplace Config
      kind: MarketplaceConfig
      name: marketplaceconfigs.marketplace.redhat.com
      version: v1alpha1
  description: "# IBM Data Reporter Operator\n\n# Introduction\n\nThe IBM Data Reporter Operator accepts events and transforms them into reports submitted to the Data Service of the IBM Metrics Operator.\n\n# Details\n\nThe IBM Data Reporter Operator deploys a service that exposes an endpoint to which callers can send raw json event data. The event data is transformed into a report and is sent to the IBM Data Service. The IBM Data Service periodically uploads the reports to Red Hat Marketplace.\n\n## Prerequisites\n\n- OpenShift Container Platform, major version 4 with any available supported minor version\n- Install IBM Metrics Operator and Red Hat Marketplace Deployment Operator\n  - IBM Data Reporter Operator prerequisties the IBM Metrics Operator data-service and registration with Red Hat Marketplace\n  - Register the Cluster by creating a `redhat-marketplace-pull-secret`, as per the instructions\n  - `rhm-data-service` has started\n\n## SecurityContextConstraints Requirements\n\n- The operator runs under Red Hat restricted SCC\n\n## Resources Required\n\n- The operator requires at least 85 Mi memory.\n\n## Limitations\n\n- Only runs on amd64, s390x and ppc64le architectures\n\n## Installing\n\n- A user with the cluster administrator role.\n- Install this operator in the same namespace as the IBM Metrics Operator and Red Hat Marketplace Deployment Operator\n  - default namespace: `redhat-marketplace`\n\n# Configuration\n\nOptional:\n- Configure the DataReporterConfig named `datareporterconfig` as per the following example\n- Reference the service account name that will be used to access the service\n  - Reports generated for events sent by this user will be decorated with the additional metadata\n\n```YAML\napiVersion: marketplace.redhat.com/v1alpha1\nkind: DataReporterConfig\nmetadata:\n  name: datareporterconfig\nspec:\n  userConfig:\n  - metadata:\n      ameta1: ametadata1\n      bmeta1: bmetadata1\n      cmeta1: cmetadata1\n      dmeta1: dmetadata1\n    userName: system:serviceaccount:openshift-redhat-marketplace:ibm-data-reporter-operator-api\n```\n\n### User Configuration\n\n- The ClusterRole for api access is `clusterrole/ibm-data-reporter-operator-api`\n- The default ServiceAccount provided as an api user is `system:serviceaccount:openshift-redhat-marketplace:ibm-data-reporter-operator-api`\n  - The default ClusterRoleBinding for this user is `clusterrolebinding/ibm-data-reporter-operator-api`\n\nOptional:\n\n- To create an additional ServiceAccount and ClusterRoleBinding for api access\n\n```SHELL\nNAMESPACE=$(oc config view --minify -o jsonpath='{..namespace}') && \\\noc create serviceaccount my-api-service-account && \\\noc create clusterrolebinding ibm-data-reporter-operator-api --clusterrole=ibm-data-reporter-operator-api --serviceaccount=${NAMESPACE}:my-api-service-account\n```\n\n- Update datareporterconfig to attach metadata to reports associated with this user\n\n## Usage\n\n- Get Token & Host\n\n```SHELL\noc project redhat-marketplace\nexport DRTOKEN=$(oc create token ibm-data-reporter-operator-api --namespace redhat-marketplace --duration 1h)\nexport DRHOST=$(oc get route ibm-data-reporter --template='{{ .spec.host }}')\n```\n\n- Get the Status\n\n```SHELL\ncurl -k -H \"Authorization: Bearer ${DRTOKEN}\" https://${DRHOST}/v1/status \n```\n\n- Post an Event\n\n```SHELL\ncurl -k -H \"Authorization: Bearer ${DRTOKEN}\" -X POST -d '{\"event\":\"myevent\"}' https://${DRHOST}/v1/event\n```\n\n## Storage\n\n- The operator temporarily stores events in pod memory, and writes to the IBM Metrics Operator data-service, which requires a PersistentVolume\n\n## License\n\nCopyright IBM Corporation 2023. All Rights Reserved.\n\nLicensed under the Apache License, Version 2.0 (the \"License\");\nyou may not use this file except in compliance with the License.\nYou may obtain a copy of the License at\n\n    http://www.apache.org/licenses/LICENSE-2.0\n\nUnless required by applicable law or agreed to in writing, software\ndistributed under the License is distributed on an \"AS IS\" BASIS,\nWITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.\nSee the License for the specific language governing permissions and\nlimitations under the License.\n"
  displayName: Data Reporter
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: true
    type: MultiNamespace
  - supported: false
    type: AllNamespaces
  keywords:
  - red hat marketplace
  - operators
  links:
  - name: V2
    url: https://v2.domain
  maturity: alpha
  provider:
    name: Red Hat Marketplace
    url: https://github.com/redhat-marketplace/redhat-marketplace-operator
  version: 0.0.0
