apiVersion: marketplace.redhat.com/v1alpha1
kind: MarketplaceConfig
metadata:
  name: marketplaceconfig
spec:
  features:
    deployment: true
    meterDefinitionCatalogServer: false
    registration: true
  installIBMCatalogSource: true
  isDisconnected: false
  license:
    accept: false

