apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    control-plane: deployer-controller-manager
    redhat.marketplace.com/name: redhat-marketplace-operator
  name: redhat-marketplace-deployer-controller-manager-metrics-service
spec:
  ports:
  - name: https
    port: 8443
    targetPort: https
  selector:
    control-plane: deployer-controller-manager
    redhat.marketplace.com/name: redhat-marketplace-operator
status:
  loadBalancer: {}
