apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  labels:
    redhat.marketplace.com/name: redhat-marketplace-operator
  name: redhat-marketplace-deployer-role
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - deploy.razee.io
  resources:
  - '*'
  verbs:
  - delete
  - get
  - list
- apiGroups:
  - rbac.authorization.k8s.io
  resourceNames:
  - razeedeploy-admin-cr
  - redhat-marketplace-razeedeploy
  resources:
  - clusterroles
  verbs:
  - delete
