apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: prometheus-operator-tls
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/name: prometheus-operator
    app.kubernetes.io/version: v0.38.1
  name: prometheus-operator
spec:
  clusterIP: None
  ports:
  - name: https
    port: 8443
    targetPort: https
  - name: web
    port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/component: controller
    app.kubernetes.io/name: prometheus-operator
