apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    service.beta.openshift.io/inject-cabundle: "true"
  labels:
    redhat.marketplace.com/name: metrics-operator
  name: metrics-operator-serving-certs-ca-bundle
