apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: rhm-dqlite
spec:
  port:
    targetPort: https
  to:
    kind: Service
    name: rhm-dqlite
  tls:
    termination: reencrypt
    insecureEdgeTerminationPolicy: Redirect