apiVersion: v1
kind: Service
metadata:
  name: rhm-dqlite
  labels:
    app: rhm-dqlite
spec:
  ports:
  - port: 8001
    name: api
  - port: 9001
    name: db
  selector:
    app: rhm-dqlite