apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: rhm-dqlite-tls
  name: rhm-dqlite
  labels:
    app: rhm-dqlite
spec:
  ports:
  - name: api
    port: 8001
    protocol: TCP
    targetPort: 8001
  - name: https
    port: 8002
    protocol: TCP
    targetPort: 8002
  - name: db
    port: 9001
    protocol: TCP
    targetPort: 9001
  selector:
    app: rhm-dqlite