---
# Source: redhat-marketplace-operator-template-chart/templates/role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: remoteresources3deployment
rules:
  - apiGroups:
      - operators.coreos.com
    resources:
      - subscriptions
    verbs:
      - '*'
  - apiGroups:
      - marketplace.redhat.com
    resources:
      - remoteresources3s
    verbs:
      - get
      - list
      - watch
  - apiGroups:
    - authentication.k8s.io
    resources:
    - tokenreviews
    verbs:
    - create
---
# Source: redhat-marketplace-operator-template-chart/templates/role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: watch-keeper
rules:
- apiGroups:
  - '*'
  resources:
  - configmaps
  - namespaces
  - nodes
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  - replicasets
  verbs:
  - get
  - list
  - watch  
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - operators.coreos.com
  resources:
  - clusterserviceversions
  - subscriptions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - config.openshift.io
  resources:
  - clusterversions
  - infrastructures
  - consoles
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - marketplace.redhat.com
  resources:
  - marketplaceconfigs
  verbs:
  - get
  - list
  - watch 
- nonResourceURLs:
  - '*'
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
---
# Source: redhat-marketplace-operator-template-chart/templates/role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: remoteresources3deployment
  namespace: system
rules:
  - apiGroups:
      - ''
    resources:
      - pods
      - secrets
    verbs:
      - get
      - watch
      - list
  - apiGroups:
      - marketplace.redhat.com
    resources:
      - remoteresources3s
      - remoteresources3s/status
    verbs:
      - '*'      
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: servicemonitor-metrics-reader
  namespace: system
rules:
  - nonResourceURLs:
    - /metrics
    verbs:
      - get